/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-secondary-fixed-variant": "#474746",
        "on-surface-variant": "#5b4039",
        "surface-variant": "#e1e3e4",
        "on-tertiary": "#ffffff",
        "inverse-surface": "#2e3132",
        "on-background": "#191c1d",
        "on-surface": "#191c1d",
        "surface": "#f8f9fa",
        "on-tertiary-fixed-variant": "#604100",
        "on-primary-fixed": "#3b0900",
        "error-container": "#ffdad6",
        "primary": "#b12d00",
        "on-tertiary-fixed": "#281900",
        "error": "#ba1a1a",
        "surface-bright": "#f8f9fa",
        "tertiary-fixed-dim": "#ffba38",
        "inverse-on-surface": "#f0f1f2",
        "on-primary": "#ffffff",
        "surface-container-low": "#f3f4f5",
        "on-secondary-container": "#636262",
        "on-error": "#ffffff",
        "on-error-container": "#93000a",
        "inverse-primary": "#ffb5a0",
        "secondary-container": "#e2dfde",
        "tertiary-fixed": "#ffdeac",
        "background": "#f8f9fa",
        "surface-tint": "#b12d00",
        "on-primary-fixed-variant": "#872000",
        "secondary-fixed": "#e5e2e1",
        "primary-fixed-dim": "#ffb5a0",
        "tertiary": "#7e5700",
        "tertiary-container": "#c08600",
        "outline": "#907067",
        "surface-container-lowest": "#ffffff",
        "primary-container": "#ff5725",
        "surface-container": "#edeeef",
        "on-tertiary-container": "#3a2600",
        "primary-fixed": "#ffdbd1",
        "surface-container-highest": "#e1e3e4",
        "surface-dim": "#d9dadb",
        "surface-container-high": "#e7e8e9",
        "secondary-fixed-dim": "#c8c6c5",
        "on-secondary": "#ffffff",
        "outline-variant": "#e4beb4",
        "on-primary-container": "#541100",
        "on-secondary-fixed": "#1b1c1c",
        "secondary": "#5f5e5e"
      },
      fontFamily: {
        headline: ["Manrope", "sans-serif"],
        body: ["Inter", "sans-serif"],
        label: ["Inter", "sans-serif"]
      },
      borderRadius: {
        "DEFAULT": "1rem",
        "lg": "2rem",
        "xl": "3rem",
        "full": "9999px"
      },
    },
  },
  plugins: [],
}
